apiVersion: v1
kind: Service
metadata:
  name: book-catalog-service
spec:
  selector:
    app: book-catalog
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: inventory-management-service
spec:
  selector:
    app: inventory-management
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort
